version: "3.8"

services:
  app:
    image: todo
    build: .
    restart: on-failure
    environment:
      APP_ENV: ${APP_ENV}
      SECRET_KEY: ${APP_SECRET_KEY}
      DATABASE_URI: postgresql+psycopg2://${DB_USER}:${DB_PASS}@db:5432/${DB_NAME}
    volumes:
      - ./migrations:/opt/app/migrations
      - ./todo:/opt/app/todo
    ports:
      - ${APP_PUBLIC_HOST}:${APP_PUBLIC_PORT}:5000

  db:
    image: postgres:14
    restart: on-failure
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASS}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - db_data:/data
    ports:
      - ${DB_PUBLIC_HOST}:${DB_PUBLIC_PORT}:5432

volumes:
  db_data:
